# Importing packages

In [ ]:
import numpy as np
from scipy import sparse as sp
import scipy.sparse.linalg

# Bit Flipping algorithm

In [10]:
def gallagerA(H, err_codeword, n_iter):
  """
  Parameters:
  H: parity check matrix (sparse matrix)
  err_codeword: transmitted codeword
  n_iter: number of iterations
  Returns
  Corrected code if found within the given number of iterations, n_iter;
  along with the iteration step it was found.
  """
  # H = sp.csr_matrix(H)
  corrected_codeword = err_codeword
  for i in range(n_iter):
    syndrome = H.dot(corrected_codeword) % 2
    unsatisfied_check_indices = np.where(syndrome == 1)[0]
    print(unsatisfied_check_indices)
    if np.sum(syndrome) == 0:
      print("Corrected codeword")
      return corrected_codeword, i
    no_ones = np.sum(H, axis=0)
    # for syn, j in enumerate(syndrome):
    #   if syn ==
  return corrected_codeword, n_iter

if __name__ == "__main__":
    H = np.array([
        [1, 1, 0, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [1, 1, 1, 0, 0, 1]
    ])

    original_codeword = np.array([0, 0, 0, 0, 0, 0])
    error_pattern = np.array([0, 1, 0, 0, 0, 0])
    received_codeword = (original_codeword + error_pattern)%2

    print("Original Codeword:", original_codeword)
    print("Received Codeword:", received_codeword)

    decoded_codeword, iterations = gallagerA(H, received_codeword, 100)

    print("Decoded Codeword:", decoded_codeword)
    print("Iterations:", iterations)

    # print(H.dot(decoded_codeword) % 2)
    no_ones = np.sum(H, axis=0)
    print(no_ones)

Original Codeword: [0 0 0 0 0 0]
Received Codeword: [0 1 0 0 0 0]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
Decoded Codeword: [0 1 0 0 0 0]
Iterations: 100
[2 3 2 1 1 1]


In [8]:
import numpy as np
from itertools import combinations

def find_common_variable_nodes(H, syndrome):
    """
    Find common variable nodes connected to unsatisfied check nodes.

    Parameters:
        H (numpy.ndarray): Parity-check matrix (m x n).
        syndrome (numpy.ndarray): Syndrome vector (1 x m).

    Returns:
        dict: A dictionary where keys are common variable node indices and values are their counts.
    """
    # Step 1: Find indices where syndrome is 1 (unsatisfied check nodes)
    unsatisfied_check_indices = np.where(syndrome == 1)[0]
    num_unsatisfied = len(unsatisfied_check_indices)

    # Dictionary to store common variable nodes and their counts
    common_variable_counts = {}

    # Set to keep track of check nodes that have already been processed in larger combinations
    processed_check_nodes = set()

    # Step 2: Check for common variable nodes in all possible combinations of unsatisfied check nodes
    if num_unsatisfied > 0:
        # Start with the largest combination (all unsatisfied check nodes) and work down to pairs
        for r in range(num_unsatisfied, 1, -1):
            # Generate all combinations of size r
            for combo in combinations(unsatisfied_check_indices, r):
                # Skip if any check node in this combination has already been processed
                if any(check_node in processed_check_nodes for check_node in combo):
                    continue
                else:
                  # Get the variable nodes for the current combination of check nodes
                  variable_node_sets = []
                  for check_index in combo:
                      row = H[check_index, :]
                      variable_nodes = np.where(row == 1)[0]
                      variable_node_sets.append(set(variable_nodes))

                  # Find intersection (common variable nodes for this combination)
                  common_nodes = set.intersection(*variable_node_sets)

                  # If common variable nodes are found, update the dictionary and mark check nodes as processed
                  if common_nodes:
                      for var_node in common_nodes:
                          if var_node in common_variable_counts:
                              common_variable_counts[var_node] += 1
                          else:
                              common_variable_counts[var_node] = 1

                      # Mark all check nodes in this combination as processed
                      processed_check_nodes.update(combo)

    return common_variable_counts

# Example Usage
if __name__ == "__main__":
    # Define a parity-check matrix H
    H = np.array([
        [1, 1, 0, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [1, 0, 0, 0, 1, 1],
        [0, 0, 1, 1, 0, 1]
    ])

    # Define a syndrome vector
    syndrome = np.array([1, 1, 0, 1])  # Example syndrome with unsatisfied check nodes

    print("Parity-Check Matrix H:")
    print(H)
    print("Syndrome:", syndrome)

    # Find common variable nodes and their counts
    common_variable_counts = find_common_variable_nodes(H, syndrome)

    print("Common Variable Nodes and Their Counts:")
    print(common_variable_counts)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 112)

In [6]:
import numpy as np
from itertools import combinations

def find_common_variable_nodes(H, syndrome):
    """
    Find common variable nodes connected to unsatisfied check nodes.

    Parameters:
        H (numpy.ndarray): Parity-check matrix (m x n).
        syndrome (numpy.ndarray): Syndrome vector (1 x m).

    Returns:
        dict: A dictionary where keys are common variable node indices and values are their counts.
    """
    # Step 1: Find indices where syndrome is 1 (unsatisfied check nodes)
    unsatisfied_check_indices = np.where(syndrome == 1)[0]
    num_unsatisfied = len(unsatisfied_check_indices)

    # Dictionary to store common variable nodes and their counts
    common_variable_counts = {}

    # Step 2: Check for common variable nodes in all possible combinations of unsatisfied check nodes
    if num_unsatisfied > 0:
        # Start with the largest combination (all unsatisfied check nodes) and work down to pairs
        for r in range(num_unsatisfied, 1, -1):
            # Generate all combinations of size r
            for combo in combinations(unsatisfied_check_indices, r):
                # Get the variable nodes for the current combination of check nodes
                variable_node_sets = []
                for check_index in combo:
                    row = H[check_index, :]
                    variable_nodes = np.where(row == 1)[0]
                    variable_node_sets.append(set(variable_nodes))

                # Find intersection (common variable nodes for this combination)
                common_nodes = set.intersection(*variable_node_sets)

                # Update the dictionary with counts
                for var_node in common_nodes:
                    if var_node in common_variable_counts:
                        common_variable_counts[var_node] += 1
                    else:
                        common_variable_counts[var_node] = 1

    return common_variable_counts

# Example Usage
if __name__ == "__main__":
    # Define a parity-check matrix H
    H = np.array([
        [1, 1, 0, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [1, 0, 0, 0, 1, 1],
        [0, 0, 1, 1, 0, 1]
    ])

    # Define a syndrome vector
    syndrome = np.array([1, 1, 0, 1])  # Unsatisfied check nodes: 0, 1, 3

    print("Parity-Check Matrix H:")
    print(H)
    print("Syndrome:", syndrome)

    # Find common variable nodes and their counts
    common_variable_counts = find_common_variable_nodes(H, syndrome)

    print("Common Variable Nodes and Their Counts:")
    print(common_variable_counts)

Parity-Check Matrix H:
[[1 1 0 1 0 0]
 [0 1 1 0 1 0]
 [1 0 0 0 1 1]
 [0 0 1 1 0 1]]
Syndrome: [1 1 0 1]
Common Variable Nodes and Their Counts:
{1: 1, 3: 1, 2: 1}


In [14]:
import numpy as np
from itertools import combinations

def find_common_variable_nodes(H, syndrome):
    """
    Find common variable nodes connected to unsatisfied check nodes.

    Parameters:
        H (numpy.ndarray): Parity-check matrix (m x n).
        syndrome (numpy.ndarray): Syndrome vector (1 x m).

    Returns:
        dict: A dictionary where keys are common variable node indices and values are their counts.
    """
    # Step 1: Find indices where syndrome is 1 (unsatisfied check nodes)
    unsatisfied_check_indices = np.where(syndrome == 1)[0]
    num_unsatisfied = len(unsatisfied_check_indices)

    # Dictionary to store common variable nodes and their counts
    common_variable_counts = {}

    # Set to keep track of processed combinations of check nodes
    processed_combinations = set()

    # Step 2: Check for common variable nodes in all possible combinations of unsatisfied check nodes
    if num_unsatisfied > 0:
        # Start with the largest combination (all unsatisfied check nodes) and work down to pairs
        for r in range(num_unsatisfied, 1, -1):
            # Generate all combinations of size r
            for combo in combinations(unsatisfied_check_indices, r):
                # Skip if this combination is a subset of any previously processed combination
                if any(set(combo).issubset(processed) for processed in processed_combinations):
                    continue

                # Get the variable nodes for the current combination of check nodes
                variable_node_sets = []
                for check_index in combo:
                    row = H[check_index, :]
                    variable_nodes = np.where(row == 1)[0]
                    variable_node_sets.append(set(variable_nodes))

                # Find intersection (common variable nodes for this combination)
                common_nodes = set.intersection(*variable_node_sets)

                # If common variable nodes are found, update the dictionary and mark the combination as processed
                if common_nodes:
                    for var_node in common_nodes:
                        if var_node in common_variable_counts:
                            common_variable_counts[var_node] += 1
                        else:
                            common_variable_counts[var_node] = 1

                    # Mark this combination as processed
                    processed_combinations.add(frozenset(combo))

    return common_variable_counts

# Example Usage
if __name__ == "__main__":
    # Define a parity-check matrix H
    # H = np.array([
    #     [1, 1, 0, 1, 0, 0],
    #     [0, 1, 1, 0, 1, 0],
    #     [1, 0, 0, 0, 1, 1],
    #     [0, 0, 1, 1, 0, 1]
    # ])

    # # Define a syndrome vector
    # syndrome = np.array([1, 1, 0, 1])  # Unsatisfied check nodes: 0, 1, 3

    print("Parity-Check Matrix H:")
    print(H)
    print("Syndrome:", syndrome)

    # Find common variable nodes and their counts
    common_variable_counts = find_common_variable_nodes(H, syndrome)

    print("Common Variable Nodes and Their Counts:")
    print(common_variable_counts)

Parity-Check Matrix H:
[[1 1 0 1 0 0]
 [0 1 1 0 1 0]
 [1 1 1 0 0 1]]
Syndrome: [0 1 0]
Common Variable Nodes and Their Counts:
{}


In [17]:
import numpy as np
from itertools import combinations

def find_common_variable_nodes(H, syndrome):
    """
    Find common variable nodes connected to unsatisfied check nodes.

    Parameters:
        H (numpy.ndarray): Parity-check matrix (m x n).
        syndrome (numpy.ndarray): Syndrome vector (1 x m).

    Returns:
        dict: A dictionary where keys are variable node indices and values are their counts.
    """
    # Check for invalid input dimensions
    m, n = H.shape
    if len(syndrome) != m:
        raise ValueError("Dimensions of H and syndrome do not match.")

    # Step 1: Find indices where syndrome is non-zero (unsatisfied check nodes)
    unsatisfied_check_indices = np.where(syndrome != 0)[0]
    num_unsatisfied = len(unsatisfied_check_indices)

    # Dictionary to store variable nodes and their counts
    variable_counts = {}

    # Step 2: Handle the case where there are no unsatisfied check nodes
    if num_unsatisfied == 0:
        return variable_counts

    # Step 3: Handle the case where there is only one unsatisfied check node
    if num_unsatisfied == 1:
        # Get the unsatisfied check node
        unsatisfied_check_index = unsatisfied_check_indices[0]

        # Get the variable nodes connected to the unsatisfied check node
        unsatisfied_variable_nodes = set(np.where(H[unsatisfied_check_index, :] == 1)[0])

        # Get the satisfied check nodes
        satisfied_check_indices = np.where(syndrome == 0)[0]

        # Get the variable nodes connected to the satisfied check nodes
        satisfied_variable_nodes = set()
        for check_index in satisfied_check_indices:
            satisfied_variable_nodes.update(np.where(H[check_index, :] == 1)[0])

        # Find variable nodes that are connected to the unsatisfied check node but not to any satisfied check node
        uncommon_variable_nodes = unsatisfied_variable_nodes - satisfied_variable_nodes

        # Update the dictionary
        for var_node in uncommon_variable_nodes:
            variable_counts[var_node] = 1

        return variable_counts

    # Step 4: Check for common variable nodes in all possible combinations of unsatisfied check nodes
    if num_unsatisfied > 1:
        # Set to keep track of processed combinations of check nodes
        processed_combinations = set()

        # Start with the largest combination (all unsatisfied check nodes) and work down to pairs
        for r in range(num_unsatisfied, 1, -1):
            # Generate all combinations of size r
            for combo in combinations(unsatisfied_check_indices, r):
                # Skip if this combination is a subset of any previously processed combination
                if any(set(combo).issubset(processed) for processed in processed_combinations):
                    continue

                # Get the variable nodes for the current combination of check nodes
                variable_node_sets = []
                for check_index in combo:
                    row = H[check_index, :]
                    variable_nodes = np.where(row == 1)[0]
                    variable_node_sets.append(set(variable_nodes))

                # Find intersection (common variable nodes for this combination)
                common_nodes = set.intersection(*variable_node_sets)

                # If common variable nodes are found, update the dictionary and mark the combination as processed
                if common_nodes:
                    for var_node in common_nodes:
                        if var_node in variable_counts:
                            variable_counts[var_node] += 1
                        else:
                            variable_counts[var_node] = 1

                    # Mark this combination as processed
                    processed_combinations.add(frozenset(combo))

    return variable_counts

# Example Usage
if __name__ == "__main__":
    # Define a parity-check matrix H
    # H = np.array([
    #     [1, 1, 0, 1, 0, 0],
    #     [0, 1, 1, 0, 1, 0],
    #     [1, 1, 1, 0, 0, 1]
    # ])

    # # Define a syndrome vector
    # syndrome = np.array([0, 1, 0])  # Unsatisfied check node: 1

    H = np.array([
        [1, 1, 0, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [1, 0, 0, 0, 1, 1],
        [0, 0, 1, 1, 0, 1]
    ])

    # Define a syndrome vector
    syndrome = np.array([0, 0, 0, 0])  # Unsatisfied check nodes: 0, 1, 3


    print("Parity-Check Matrix H:")
    print(H)
    print("Syndrome:", syndrome)

    # Find variable nodes and their counts
    variable_counts = find_common_variable_nodes(H, syndrome)

    print("Variable Nodes and Their Counts:")
    print(variable_counts)

Parity-Check Matrix H:
[[1 1 0 1 0 0]
 [0 1 1 0 1 0]
 [1 0 0 0 1 1]
 [0 0 1 1 0 1]]
Syndrome: [0 0 0 0]
Variable Nodes and Their Counts:
{}


In [23]:
import numpy as np
from itertools import combinations

def find_common_variable_nodes(H, syndrome):
    """
    Find common variable nodes connected to unsatisfied check nodes.

    Parameters:
        H (numpy.ndarray): Parity-check matrix (m x n).
        syndrome (numpy.ndarray): Syndrome vector (1 x m).

    Returns:
        dict: A dictionary where keys are variable node indices and values are their counts.
    """
    # Check for invalid input dimensions
    m, n = H.shape
    if len(syndrome) != m:
        raise ValueError("Dimensions of H and syndrome do not match.")

    # Step 1: Find indices where syndrome is non-zero (unsatisfied check nodes)
    unsatisfied_check_indices = np.where(syndrome != 0)[0]
    num_unsatisfied = len(unsatisfied_check_indices)

    # Dictionary to store variable nodes and their counts
    variable_counts = {}

    # Step 2: Handle the case where there are no unsatisfied check nodes
    if num_unsatisfied == 0:
        return variable_counts

    # Step 3: Handle the case where there is only one unsatisfied check node
    if num_unsatisfied == 1:
        # Get the unsatisfied check node
        unsatisfied_check_index = unsatisfied_check_indices[0]

        # Get the variable nodes connected to the unsatisfied check node
        unsatisfied_variable_nodes = set(np.where(H[unsatisfied_check_index, :] == 1)[0])

        # Get the satisfied check nodes
        satisfied_check_indices = np.where(syndrome == 0)[0]

        # Get the variable nodes connected to the satisfied check nodes
        satisfied_variable_nodes = set()
        for check_index in satisfied_check_indices:
            satisfied_variable_nodes.update(np.where(H[check_index, :] == 1)[0])

        # Find variable nodes that are connected to the unsatisfied check node but not to any satisfied check node
        uncommon_variable_nodes = unsatisfied_variable_nodes - satisfied_variable_nodes

        # Update the dictionary
        for var_node in uncommon_variable_nodes:
            variable_counts[var_node] = 1

        return variable_counts

    # Step 4: Check for common variable nodes in all possible combinations of unsatisfied check nodes
    if num_unsatisfied > 1:
        # Set to keep track of processed combinations of check nodes
        processed_combinations = set()

        # Start with the largest combination (all unsatisfied check nodes) and work down to pairs
        for r in range(num_unsatisfied, 1, -1):
            # Generate all combinations of size r
            for combo in combinations(unsatisfied_check_indices, r):
                # Skip if this combination is a subset of any previously processed combination
                if any(set(combo).issubset(processed) for processed in processed_combinations):
                    continue

                # Get the variable nodes for the current combination of check nodes
                variable_node_sets = []
                for check_index in combo:
                    row = H[check_index, :]
                    variable_nodes = np.where(row == 1)[0]
                    variable_node_sets.append(set(variable_nodes))

                # Find intersection (common variable nodes for this combination)
                common_nodes = set.intersection(*variable_node_sets)

                # If common variable nodes are found, update the dictionary and mark the combination as processed
                if common_nodes:
                    for var_node in common_nodes:
                        if var_node in variable_counts:
                            variable_counts[var_node] += 1
                        else:
                            variable_counts[var_node] = 1

                    # Mark this combination as processed
                    processed_combinations.add(frozenset(combo))

    return variable_counts

def flip_variable_nodes(H, syndrome, received_codeword):
    """
    Flip variable nodes in the received codeword based on the threshold (number of ones in each column of H).

    Parameters:
        H (numpy.ndarray): Parity-check matrix (m x n).
        syndrome (numpy.ndarray): Syndrome vector (1 x m).
        received_codeword (numpy.ndarray): Received codeword (1 x n).

    Returns:
        numpy.ndarray: Decoded codeword (1 x n).
    """
    # Step 1: Find common variable nodes and their counts
    variable_counts = find_common_variable_nodes(H, syndrome)
    print(variable_counts)

    # Step 2: Compute the threshold for each variable node (number of ones in each column of H)
    thresholds = np.sum(H, axis=0)

    # Step 3: Initialize the decoded codeword as a copy of the received codeword
    decoded_codeword = received_codeword.copy()

    # Step 4: Flip variable nodes where the count exceeds or equals the threshold
    for var_node, count in variable_counts.items():
        if count >= thresholds[var_node]:
            decoded_codeword[var_node] = 1 - decoded_codeword[var_node]
        print(var_node)
        print(count)

    return decoded_codeword

# Example Usage
if __name__ == "__main__":
    # Define a parity-check matrix H
    # H = np.array([
    #     [1, 1, 0, 1, 0, 0],
    #     [0, 1, 1, 0, 1, 0],
    #     [1, 1, 1, 0, 0, 1]
    # ])

    H = np.array([
        [1, 1, 0, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [1, 0, 0, 0, 1, 1],
        [0, 0, 1, 1, 0, 1]
    ])


    # Define the original codeword and error pattern
    original_codeword = np.array([0, 0, 0, 0, 0, 0])
    error_pattern = np.array([0, 1, 0, 0, 0, 0])

    # Compute the received codeword
    received_codeword = (original_codeword + error_pattern) % 2

    print("Original Codeword:", original_codeword)
    print("Error Pattern:", error_pattern)
    print("Received Codeword:", received_codeword)

    # Compute the syndrome
    syndrome = np.mod(H @ received_codeword, 2)

    print("Syndrome:", syndrome)

    # Flip variable nodes based on the threshold
    decoded_codeword = flip_variable_nodes(H, syndrome, received_codeword)

    print("Decoded Codeword:")
    print(decoded_codeword)

Original Codeword: [0 0 0 0 0 0]
Error Pattern: [0 1 0 0 0 0]
Received Codeword: [0 1 0 0 0 0]
Syndrome: [1 1 0 0]
{1: 1}
1
1
Decoded Codeword:
[0 1 0 0 0 0]


In [25]:
import numpy as np
from itertools import combinations

def find_common_variable_nodes(H, syndrome):
    """
    Find common variable nodes connected to unsatisfied check nodes.

    Parameters:
        H (numpy.ndarray): Parity-check matrix (m x n).
        syndrome (numpy.ndarray): Syndrome vector (1 x m).

    Returns:
        dict: A dictionary where keys are variable node indices and values are their counts.
    """
    # Check for invalid input dimensions
    m, n = H.shape
    if len(syndrome) != m:
        raise ValueError("Dimensions of H and syndrome do not match.")

    # Step 1: Find indices where syndrome is non-zero (unsatisfied check nodes)
    unsatisfied_check_indices = np.where(syndrome != 0)[0]
    num_unsatisfied = len(unsatisfied_check_indices)

    # Dictionary to store variable nodes and their counts
    variable_counts = {}

    # Step 2: Handle the case where there are no unsatisfied check nodes
    if num_unsatisfied == 0:
        return variable_counts

    # Step 3: Handle the case where there is only one unsatisfied check node
    if num_unsatisfied == 1:
        # Get the unsatisfied check node
        unsatisfied_check_index = unsatisfied_check_indices[0]

        # Get the variable nodes connected to the unsatisfied check node
        unsatisfied_variable_nodes = set(np.where(H[unsatisfied_check_index, :] == 1)[0])

        # Get the satisfied check nodes
        satisfied_check_indices = np.where(syndrome == 0)[0]

        # Get the variable nodes connected to the satisfied check nodes
        satisfied_variable_nodes = set()
        for check_index in satisfied_check_indices:
            satisfied_variable_nodes.update(np.where(H[check_index, :] == 1)[0])

        # Find variable nodes that are connected to the unsatisfied check node but not to any satisfied check node
        uncommon_variable_nodes = unsatisfied_variable_nodes - satisfied_variable_nodes

        # Update the dictionary
        for var_node in uncommon_variable_nodes:
            variable_counts[var_node] = 1

        return variable_counts

    # Step 4: Check for common variable nodes in all possible combinations of unsatisfied check nodes
    if num_unsatisfied > 1:
        # Set to keep track of processed combinations of check nodes
        processed_combinations = set()

        # Start with the largest combination (all unsatisfied check nodes) and work down to pairs
        for r in range(num_unsatisfied, 1, -1):
            # Generate all combinations of size r
            for combo in combinations(unsatisfied_check_indices, r):
                # Skip if this combination is a subset of any previously processed combination
                if any(set(combo).issubset(processed) for processed in processed_combinations):
                    continue

                # Get the variable nodes for the current combination of check nodes
                variable_node_sets = []
                for check_index in combo:
                    row = H[check_index, :]
                    variable_nodes = np.where(row == 1)[0]
                    variable_node_sets.append(set(variable_nodes))

                # Find intersection (common variable nodes for this combination)
                common_nodes = set.intersection(*variable_node_sets)

                # If common variable nodes are found, update the dictionary and mark the combination as processed
                if common_nodes:
                    for var_node in common_nodes:
                        if var_node in variable_counts:
                            variable_counts[var_node] += len(combo)  # Increment by the size of the combination
                        else:
                            variable_counts[var_node] = len(combo)  # Initialize with the size of the combination

                    # Mark this combination as processed
                    processed_combinations.add(frozenset(combo))

    return variable_counts

def flip_variable_nodes(H, syndrome, received_codeword):
    """
    Flip variable nodes in the received codeword based on the threshold (number of ones in each column of H).

    Parameters:
        H (numpy.ndarray): Parity-check matrix (m x n).
        syndrome (numpy.ndarray): Syndrome vector (1 x m).
        received_codeword (numpy.ndarray): Received codeword (1 x n).

    Returns:
        numpy.ndarray: Decoded codeword (1 x n).
    """
    # Step 1: Find common variable nodes and their counts
    variable_counts = find_common_variable_nodes(H, syndrome)

    # Step 2: Compute the threshold for each variable node (number of ones in each column of H)
    thresholds = np.sum(H, axis=0)

    # Step 3: Initialize the decoded codeword as a copy of the received codeword
    decoded_codeword = received_codeword.copy()

    # Step 4: Flip variable nodes where the count exceeds or equals the threshold
    for var_node, count in variable_counts.items():
        if count >= thresholds[var_node]:
            decoded_codeword[var_node] = 1 - decoded_codeword[var_node]

    return decoded_codeword

# Example Usage
if __name__ == "__main__":
    # Define a parity-check matrix H
    # H = np.array([
    #     [1, 1, 0, 1, 0, 0],
    #     [0, 1, 1, 0, 1, 0],
    #     [1, 1, 1, 0, 0, 1]
    # ])
    H = np.array([
        [1, 1, 0, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [1, 0, 0, 0, 1, 1],
        [0, 0, 1, 1, 0, 1]
    ])
    # Define the original codeword and error pattern
    original_codeword = np.array([0, 0, 0, 0, 0, 0])
    error_pattern = np.array([0, 1, 0, 0, 0, 0])

    # Compute the received codeword
    received_codeword = (original_codeword + error_pattern) % 2

    print("Original Codeword:", original_codeword)
    print("Error Pattern:", error_pattern)
    print("Received Codeword:", received_codeword)

    # Compute the syndrome
    syndrome = np.mod(H @ received_codeword, 2)

    print("Syndrome:", syndrome)

    # Flip variable nodes based on the threshold
    decoded_codeword = flip_variable_nodes(H, syndrome, received_codeword)

    print("Decoded Codeword:")
    print(decoded_codeword)

Original Codeword: [0 0 0 0 0 0]
Error Pattern: [0 1 0 0 0 0]
Received Codeword: [0 1 0 0 0 0]
Syndrome: [1 1 0 0]
Decoded Codeword:
[0 0 0 0 0 0]
